window (new|open): app.window_open()
window next: app.window_next()
window last: app.window_previous()
window close: app.window_close()
focus <user.running_applications>: user.switcher_focus(running_applications)
running list: user.switcher_toggle_running()
run <user.launch_applications>: user.switcher_launch(launch_applications)
last window:
    key('alt-tab')
close window: app.window_close()